file_format: "1"
id: think_corney
name: ThinkCorney
type: shield
url: https://github.com/infused-kim/kb_think_corney
requires: [seeeduino_xiao_ble]
features:
  - keys
  - display
siblings:
  - think_corney_left
  - think_corney_right
